-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.56.1;sid=FREE;port=1521

SET client_encoding TO 'UTF8';

SET search_path = sh,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW profits (channel_id, cust_id, prod_id, promo_id, time_id, unit_cost, unit_price, amount_sold, quantity_sold, total_cost) AS SELECT
  s.channel_id, 
  s.cust_id, 
  s.prod_id, 
  s.promo_id, 
  s.time_id,
  c.unit_cost, 
  c.unit_price, 
  s.amount_sold, 
  s.quantity_sold,
  c.unit_cost * s.quantity_sold TOTAL_COST
 FROM 
  costs c, sales s
 WHERE c.prod_id = s.prod_id
   AND c.time_id = s.time_id
   AND c.channel_id = s.channel_id
   AND c.promo_id = s.promo_id;


